### ISSUE TITLE
Status of Twitter/X Data

### ISSUE THREAD

**Issue by stefan-it** [mainlp/BarNER#1]
Hi @logan-siyao-peng and team,

many thanks for releasing this great resource for Bavarian!

I would like to integrate the dataset into our Flair library (see https://github.com/flairNLP/flair/issues/3533), and I inspected the dataset a bit deeper.

The Twitter/X data is not currently available, so I would like to ask if you have any plans to publicly release the Twitter data - or will this dataset only be available upon request.

Many thanks and best,

Stefan

**Comment by logan-siyao-peng** [comment]
Hi Stefan,
Thank you for your interest in BarNER and German dialects in general.
Unfortunately, we cannot share the raw text data publicly due to the Twitter/X license.
However, the data would be available upon request. 
I hope this works for you.

**Comment by stefan-it** [comment]
Hi @logan-siyao-peng ,

many thanks for your reply! I totally understand this and many thanks for exchanging the Twitter data.
